### ISSUE TITLE
A solution? Really? 

### ISSUE THREAD

**Issue by SiteSplat** [GetStream/pusher-chatkit-migration#3]
Pusher Chatkit failed because of their ridiculous pricing and unwillingness to to target forum owners even after I reached out to them to work with it with my BBchat: 
https://sitesplat.com/phpBB3/viewtopic.php?f=17&t=4761

How's a $499 (GetStream) subscription is going to work? from $99 (Chatkit) to $499?

What's so difficult to understand? We are in times where you can get a cloud server for $5 per month and have amazing services as never before. Why can you not guys understand that you need a low price package for smaller communities?  

Is it so hard to offer a basic account for let's say $10 per month? I spent thousands of dollars and countless hours to build the chat with Chatkit API only to find myself 2 years later in this predicament.  All my clients left stranded with their own communities because of this insane pricing.

**Comment by tschellenbach** [comment]
Stream is roughly 40% cheaper than competitors such as Sendbird and Pubnub. 

I realize that if you're working on a hobby project or are otherwise not paying for development time something like Stream could be too expensive. On the flipside, if you're paying for a product development team $500 a month is a modest investment.

Anyhow, I understand your situation, but at the moment we can't help you with this.

You could build your own chat with socket.io and host it on digital ocean. That's more cost effective if you're not paying for development time and don't have a lot of usage (building chat on node/socket.io is not very efficient so hosting costs eventually become higher than more efficient solutions such as Stream. Stream's tech is based on Go, RocksDB & Raft).
